version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17
    steps:
#Checkout
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker
          command: docker build -t index.js -f ./app/Dockerfile .
      - run:
          name: Test Docker
          command: docker run -d -p 3000:3000 index.js
#Fake test
      - run:
          name: Fake Test
          command: echo "Fake test"
workflows:
  version: 2
  build-test:
    jobs:
      - build
    # - deploy:
    #     requires:
    #       - test-node